import { defineConfig, devices } from '@playwright/test';

const isCI = !!process.env.CI;

/**
 * Runs a production build under the exact Content Security Policy it ships
 * with.
 *
 * The main e2e suite runs against `vite dev`, which necessarily serves a laxer
 * policy: `@vitejs/plugin-react` injects an inline preamble, so dev needs
 * `'unsafe-inline'` for scripts, and a browser ignores `'unsafe-inline'` the
 * moment a hash is present. A dev-server run therefore cannot prove the real
 * policy works, and a CSP that is even slightly wrong fails as a feature that
 * quietly stops working rather than as a test that goes red.
 *
 * `vite preview` replays the header out of `dist/staticwebapp.config.json`,
 * which is the artifact Static Web Apps serves, so what is under test here is
 * the shipped bytes rather than a second opinion about them.
 */
export default defineConfig({
  testDir: './e2e',
  testMatch: /csp\.spec\.ts/,
  fullyParallel: true,
  forbidOnly: isCI,
  retries: isCI ? 2 : 0,
  reporter: isCI ? [['github'], ['html', { open: 'never' }]] : 'list',
  use: {
    baseURL: 'http://localhost:4173',
    trace: 'on-first-retry',
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
  webServer: {
    // Always rebuild: the header under test is generated by the build, so
    // serving a stale `dist/` would test a policy that no longer exists.
    command: 'pnpm build && pnpm preview',
    url: 'http://localhost:4173',
    reuseExistingServer: false,
    timeout: 180_000,
  },
});
