/**
 * Photo bytes: naming, quota, and short-lived user-delegation SAS.
 *
 * Bytes never travel through the BFF. A photo is megabytes and a Function has
 * a request size limit and a per-second billing meter, so proxying them would
 * be slower, more expensive, and would cap the photo size at an arbitrary
 * number. The client uploads directly to Blob Storage instead, and this module
 * hands out a narrowly scoped, short-lived credential to do it with.
 *
 * The SAS is a *user-delegation* SAS, signed with a key obtained through the
 * managed identity rather than an account key. There is no account key to leak:
 * `specs/sync.md` -> Infrastructure requires the identity path throughout.
 */
import {
  BlobSASPermissions,
  BlobServiceClient,
  SASProtocol,
  generateBlobSASQueryParameters,
} from '@azure/storage-blob';
import { DefaultAzureCredential } from '@azure/identity';
import { requireEnv } from './http.js';

/** `specs/sync.md` -> Photos. */
export const PHOTO_QUOTA_BYTES = 500 * 1024 * 1024;

/**
 * Long enough to upload a photo on a slow connection, short enough that a
 * leaked URL is worthless by the time it is found.
 */
const SAS_TTL_MS = 15 * 60 * 1000;

/**
 * Clock skew allowance. Without it a client whose clock runs a minute fast
 * rejects — or Storage rejects — a token that is valid by every other measure.
 */
const SAS_SKEW_MS = 5 * 60 * 1000;

export const PHOTO_CONTAINER = 'photos';

/** Matches `infra/resources.bicep` -> `PHOTO_CONTAINER`. */
function containerName(): string {
  return process.env.PHOTO_CONTAINER ?? PHOTO_CONTAINER;
}

export class QuotaExceededError extends Error {
  constructor(
    readonly used: number,
    readonly requested: number,
    readonly quota: number,
  ) {
    super(
      `Photo storage quota exceeded: ${used} bytes used, ${requested} requested, ${quota} allowed.`,
    );
    this.name = 'QuotaExceededError';
  }
}

/**
 * Blobs are namespaced by user, which is what makes the quota countable with a
 * single prefix listing and what keeps one user's SAS from being able to name
 * another user's blob.
 *
 * The id is validated rather than escaped: ids are generated by the client, and
 * a value containing `..` or a slash could otherwise address a path outside the
 * user's prefix.
 */
export function photoBlobName(userId: string, photoId: string): string {
  if (!isSafeId(userId) || !isSafeId(photoId)) {
    throw new Error('Unsafe identifier for a blob path');
  }
  return `${userId}/${photoId}`;
}

/**
 * Conservative on purpose: ids are uuids and provider subject claims.
 *
 * The dot-only exclusion matters on its own — `.` and `..` are made entirely of
 * permitted characters, so the character class alone would admit the two path
 * segments with special meaning.
 */
export function isSafeId(value: string): boolean {
  if (value === '.' || value === '..') return false;
  return /^[A-Za-z0-9._-]{1,128}$/.test(value);
}

/**
 * Whether an upload of `requested` bytes fits.
 *
 * Pure, so the boundary conditions are testable without a storage account.
 */
export function fitsQuota(used: number, requested: number, quota = PHOTO_QUOTA_BYTES): boolean {
  if (!Number.isFinite(requested) || requested < 0) return false;
  return used + requested <= quota;
}

let service: BlobServiceClient | undefined;
let credential: DefaultAzureCredential | undefined;

function getService(): BlobServiceClient {
  if (service) return service;
  credential ??= new DefaultAzureCredential();
  service = new BlobServiceClient(
    `https://${requireEnv('PHOTO_STORAGE_ACCOUNT')}.blob.core.windows.net`,
    credential,
  );
  return service;
}

/**
 * Bytes currently stored for this user.
 *
 * Measured by listing rather than by maintaining a counter. A counter has to be
 * incremented at SAS-grant time — before the upload has actually happened — so
 * every abandoned upload inflates it permanently, and the drift is silent and
 * unrecoverable. Listing is O(photos), and photos are bounded by this very
 * quota, so the cost is bounded too.
 */
export async function usedBytes(userId: string): Promise<number> {
  const container = getService().getContainerClient(containerName());
  let total = 0;

  for await (const blob of container.listBlobsFlat({ prefix: `${userId}/` })) {
    total += blob.properties.contentLength ?? 0;
  }
  return total;
}

export interface SasGrant {
  url: string;
  expiresAt: string;
}

async function sign(
  userId: string,
  photoId: string,
  permissions: BlobSASPermissions,
): Promise<SasGrant> {
  const blobName = photoBlobName(userId, photoId);
  const now = Date.now();
  const startsOn = new Date(now - SAS_SKEW_MS);
  const expiresOn = new Date(now + SAS_TTL_MS);

  const client = getService();
  const delegationKey = await client.getUserDelegationKey(startsOn, expiresOn);

  const query = generateBlobSASQueryParameters(
    {
      containerName: containerName(),
      blobName,
      permissions,
      startsOn,
      expiresOn,
      // HTTPS only: a SAS is a bearer credential in a URL, and one sent in
      // clear text is one that anyone on the path can replay.
      protocol: SASProtocol.Https,
    },
    delegationKey,
    client.accountName,
  ).toString();

  return {
    url: `${client.getContainerClient(containerName()).getBlobClient(blobName).url}?${query}`,
    expiresAt: expiresOn.toISOString(),
  };
}

/**
 * A write-only credential for exactly one blob.
 *
 * `create` and `write` without `read` or `delete`: the client needs to put its
 * own bytes and nothing else, and photo bytes are immutable, so no legitimate
 * caller ever needs to overwrite or remove one with this grant.
 */
export function grantUpload(userId: string, photoId: string): Promise<SasGrant> {
  return sign(userId, photoId, BlobSASPermissions.from({ create: true, write: true }));
}

/** A read-only credential for exactly one blob. */
export function grantDownload(userId: string, photoId: string): Promise<SasGrant> {
  return sign(userId, photoId, BlobSASPermissions.from({ read: true }));
}

/** Whether the bytes are actually there — a metadata row can outlive them. */
export async function photoExists(userId: string, photoId: string): Promise<boolean> {
  const client = getService()
    .getContainerClient(containerName())
    .getBlobClient(photoBlobName(userId, photoId));
  return client.exists();
}

/** Test seam: drops the cached client so a new environment takes effect. */
export function resetBlobClientForTests(): void {
  service = undefined;
  credential = undefined;
}
